"""automatic migration

Revision ID: 8c239fda7e7d
Revises: 87b57dc9edd6
Create Date: 2023-11-28 14:26:15.236841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c239fda7e7d'
down_revision = '87b57dc9edd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_comments', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('max_comments')

    # ### end Alembic commands ###
