version: '3'
services:
  web:
    build: ./app
    ports:
      - "5123:5123"
    volumes:
      - ./app:/app
    depends_on:
      - db
      - mongo

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mySuperSecurePassword
      MYSQL_DATABASE: mySQLdb
    volumes:
      - ./data/mysql:/var/lib/mysql

  mongo:
    image: mongo
    volumes:
      - ./data/mongo:/data/db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: mySuperSecurePassword
    ports:
      - "8080:80"
    depends_on:
      - db

  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - "8081:8081"
    depends_on:
      - mongo
